version: 0.0
os: linux
files:
  - source: app/frontend/stylish-1.0.0
    destination: /home/ec2-user/stylish-app
hooks:
  AfterInstall:
    - location: scripts/install.sh
      timeout: 300
      runas: ec2-user
  ApplicationStart:
    - location: scripts/start.sh
      timeout: 300
      runas: ec2-user
