version: 0.2

phases:
  install:
    runtime-versions:
      docker: 20
    commands:
      - echo Installing dependencies
  build:
    commands:
      - echo Build phase complete

artifacts:
  files:
    - appspec.yml
    - scripts/**
    - app/frontend/stylish-1.0.0/**
