version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in...
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 060795913786.dkr.ecr.us-east-1.amazonaws.com
  build:
    commands:
      - echo Building Docker image...
      - cd app
      - docker build -t stylish-app .
      - docker tag stylish-app:latest 060795913786.dkr.ecr.us-east-1.amazonaws.com/cap4-app-dev:latest
  post_build:
    commands:
      - echo Pushing Docker image to ECR...
      - docker push 060795913786.dkr.ecr.us-east-1.amazonaws.com/cap4-app-dev:latest

artifacts:
  files:
    - app/**/*
