version: 0.2

phases:
  install:
    commands:
      - echo "Installing Terraform..."
      - curl -o terraform.zip https://releases.hashicorp.com/terraform/1.7.5/terraform_1.7.5_linux_amd64.zip
      - unzip terraform.zip
      - mv terraform /usr/local/bin/
      - terraform version
  build:
    commands:
      - echo "Running Terraform Init..."
      - terraform init
      - echo "Running Terraform Apply..."
      - terraform apply -auto-approve -var-file=terraform.tfvars
