version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 060795913786.dkr.ecr.us-east-1.amazonaws.com
  build:
    commands:
      - echo Build started on `date`
      - cd app/frontend
      - docker build -t cap4-app-dev .
      - docker tag cap4-app-dev:latest 060795913786.dkr.ecr.us-east-1.amazonaws.com/cap4-app-dev:latest
  post_build:
    commands:
      - echo Build completed on `date`
      - docker push 060795913786.dkr.ecr.us-east-1.amazonaws.com/cap4-app-dev:latest
