version: 0.2

env:
  secrets-manager:
    DOCKERHUB_USERNAME: dockerhub/credentials:username
    DOCKERHUB_PASSWORD: dockerhub/credentials:password

phases:
  install:
    runtime-versions:
      docker: 20
    commands:
      - echo Installing dependencies...
      - echo Checking AWS CLI version...
      - aws --version

  pre_build:
    commands:
      - echo Logging in to DockerHub...
      - echo "$DOCKERHUB_PASSWORD" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 060795913786.dkr.ecr.us-east-1.amazonaws.com

  build:
    commands:
      - echo Building Docker image...
      - cd app
      - docker build -t cap4-app-dev .
      - docker tag cap4-app-dev:latest 060795913786.dkr.ecr.us-east-1.amazonaws.com/cap4-app-dev:latest

  post_build:
    commands:
      - echo Pushing Docker image to Amazon ECR...
      - docker push 060795913786.dkr.ecr.us-east-1.amazonaws.com/cap4-app-dev:latest
